### ISSUE TITLE
Need to prohibit the control of drag and drop

### ISSUE THREAD

**Issue by DreamLi1314** [nathancahill/split#144]
**In some cases I need to manually control the left pane and the right pane to a fixed size, so I need to disable the user from dragging the resize function. We don't seem to have this feature right now.
I saw some code, but it didn't seem to work:**
``` JavaScript
function drag (e) {
   var offset;

   if (!this.dragging) { return }
.....
```

**Comment by DreamLi1314** [comment]
I modify the source code like as:
``` JavaScript
this.dragging = false;
if (!this.dragging) { return }
```
This can achieve my goal, but I can't set this.dragging outside.

**Comment by DreamLi1314** [comment]
There are also some problems with this:
- I use it in angular6, use split.destroy() will throw expretionchange error.
- nothing condition for control call destroy method.
- I needd a variable of config for control it.

now, I handle it by setSizes, like as:
``` ts
let config = {
         sizes: this.sizes,
         ...
         onDrag: (event: any) => {
            if(!this.dragEnable) {
               this.setSizes(this.sizes);
            }

            this.onDrag.emit(event);
         },
        ...
      };

      this.splitInstance = Split(children, config);
```

**Comment by nathancahill** [comment]
What is the exact error you get when you call `split.destroy?`
