### ISSUE TITLE
flex columns: elementStyle with minSize

### ISSUE THREAD

**Issue by zfrenchee** [nathancahill/split#165]
Since elementStyle only takes a percentage value, it ignores `minSize`, even when `expandToMin: true`. 

How can you set the minimum width of columns in a flex display? 

More broadly, I'd love to see documentation of how to use this library with bootstrap 4 (4.1).

**Comment by nathancahill** [comment]
What do you mean it ignores `minSize`? The `minSize` is factored in to the percentage value, it should never result in percentages less than `minSize`. If it is, please post a [jsfiddle](https://jsfiddle.net/) with the issue.

**Comment by zfrenchee** [comment]
Thanks for getting back to me @nathancahill -- unfortunately I'm going to leave this one behind -- sorry I couldn't make you a fiddle :(
