### ISSUE TITLE
Script causes errors

### ISSUE THREAD

**Issue by neahan** [nathancahill/split#166]
Added file from https://github.com/nathancahill/split/blob/master/packages/splitjs/src/split.js to website and in scripts file used following code:   

`
Split(['.c-split-pane__left', '.c-split-pane__right'], {
        sizes: [25, 75],
    })
`

Both produce following errors: 

1) split.js:756 Uncaught SyntaxError: Unexpected token export

2) scripts.js:57 Uncaught ReferenceError: Split is not defined
    at HTMLDocument.<anonymous> (scripts.js:57)
    at k (jquery.js:24)
    at Object.fireWith [as resolveWith] (jquery.js:24)
    at Function.ready (jquery.js:24)
    at HTMLDocument.g (jquery.js:14)
(anonymous) @ scripts.js:57
k @ jquery.js:24
fireWith @ jquery.js:24
ready @ jquery.js:24
g @ jquery.js:14

**Comment by nathancahill** [comment]
Split.js is no longer published on Github, that's the source code file. Here's the section of the README: https://github.com/nathancahill/split/tree/master/packages/splitjs#installation

Here's a link to the published build: https://unpkg.com/split.js/split.min.js
