### ISSUE TITLE
Can I use it in render()?

### ISSUE THREAD

**Issue by wandonye** [nathancahill/split#167]
I'm using `react-split`. Is it supposed to work if I do:
```
return (
  <Split >
            <component1 />
            <component2 />
    </Split>
)
```

It is not showing any of my components currently. I'd like to make sure it's some setting incorrect or the way I'm using it is wrong. With 
```
ReactDOM.render(
    <Split>
        <Component />
        <Component />
    </Split>
)
```
it doesn't fit into my codes.

**Comment by nathancahill** [comment]
Yes, the code you posted is just an example. It should work as you have it.

**Comment by nathancahill** [comment]
Just updated the readme to make the example less confusing.
