### ISSUE TITLE
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `SplitWrapper`, expected a single ReactElement.

### ISSUE THREAD

**Issue by av1ctor** [nathancahill/split#169]
Just updated to React 16.6.1 and it started to report that warning.

At https://github.com/nathancahill/split/blob/master/packages/react-split/src/index.js#L161, the correct shouldn't be:

children: PropTypes.arrayOf(PropTypes.element)

?

**Comment by nathancahill** [comment]
Yes indeed. Want to submit that change as a PR?
