### ISSUE TITLE
add Draggable to the options

### ISSUE THREAD

**Issue by TheSpartaPT** [nathancahill/split#172]
this parameter would be a boolean and would decide if the gutter would be able to move or not, this would be usefull if you only want to split and not be able to drag.

when calling Split it would look something like this:

    Split(["#a1", "#a2"], {
        direction: 'vertical',
        sizes: [50, 50],
        draggable: true, // or false    <---------------------------
        gutterSize: 8,
        cursor: 'row-resize'
    });

**Comment by nathancahill** [comment]
You can create the Split and then immediately call `destroy(true, true)` to preserve the styles and the gutter element: [splitjs#destroy](https://github.com/nathancahill/split/tree/master/packages/splitjs#destroypreservestyles--false-preservegutters--false)
