### ISSUE TITLE
split-grid: improve incomplete documentation

### ISSUE THREAD

**Issue by michael-brade** [nathancahill/split#173]
I love split-grid :smile: and just ported my code to it. But I had to read the source to understand it...
The reason was that the docs are a bit misleading:
Under https://github.com/nathancahill/split/tree/master/packages/split-grid#migrating-from-splitjs the example is incomplete. It should probably read:
```
<div class="grid">
    <div class="column-1"></div>
    <div class="gutter"></div>
    <div class="column-2"></div>
    <div class="row-1"></div>
</div>
```
and the JS:
```
Split({ // gutters specified in options
    columnGutters: [{
        track: 1,
        element: document.querySelector('.gutter'),
    }]
})
```
And a bit further down, there is:
```
<div style="grid-template-columns: 50% 50%"></div>
```
But the gutter actually has to be part of the template, so for two columns it should probably be something like `"grid-template-columns: 1fr 5px 1fr"`.

**Comment by nathancahill** [comment]
Good feedback! Will improve with those updates.

**Comment by nathancahill** [comment]
@dragontheory Flexbox is supported in Split.js: https://github.com/nathancahill/split/tree/master/packages/splitjs#flex-layout
