### ISSUE TITLE
License unknown, link to license on website broken

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [nathancahill/split#182]
There is no license file in the repository or any reference to a license within the project GitHub. The link on the website [https://split.js.org/](https://split.js.org/) is also not properly working. 

There is a reference to MIT in the package.json, but since the license file has been removed, this doesn't add much clarity. Did you forget to add the LICENSE.md or did you forget to remove the 'MIT' license from the package.json?

This causes an license uncertainty which should be resolved before I and others can use the library.

**Comment by nathancahill** [comment]
Thanks. Each of the packages has a MIT license in their directory. I added another license file at the top level of the repo to avoid any confusion.
