### ISSUE TITLE
Make 'sizes' optional or specify sizes in rem

### ISSUE THREAD

**Issue by minogin** [nathancahill/split#184]
I have a layout where the left panel is 10rem and the right fills the rest. This was achieved by:
```
.left {
  flex: 0 0 10rem;
}
.right {
  flex: 1 1 auto;
}
```
How could I apply split to this layout? I cannot use '11rem' and 'auto' in 'sizes' option.

**Comment by nathancahill** [comment]
You can calculate what percentage `10rem` is of the parent, and use that to set the initial sizes.
