### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by fgeorges** [nathancahill/split#192]
I am trying to use Split.js, as well as Split Grid.  I used the examples in the respective README files, as well as in a few issues on GitHub.  But when I put the README example up together, it looks like `Split` is not executed at all.

In the case of Split.js, it gives me the following on the page (that is, the expected output from plain HTML):

    content one
    content two
    content three

For the Split Grid example, nothing is shown (here again, that's what is expected from the HTML alone).

I put both examples resp. here (links show the code and result, and link to the Gist on GitHub):

- https://bl.ocks.org/fgeorges/b2f7a007a30395b54715df8c5eaf7dda
- https://bl.ocks.org/fgeorges/2de98a6fc77e363b0c1bb1ed8ef57db0

Is there anything wrong?  Is there any such example available somewhere? (I've looked for, but I might have missed them)  Thank you!

Here are both examples as well for reference:

**Split.js index.html**

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Split panels</title>
      <script type="text/javascript" src="https://unpkg.com/split.js/dist/split.min.js"></script>
    </head>
    <body>
      <div>
        <div id="one">content one</div>
        <div id="two">content two</div>
        <div id="three">content three</div>
      </div>
    </body>
    <script type="text/javascript">
      window.onload = function() {
        Split(['#one', '#two'], {
          sizes: [25, 75],
          minSize: 200
        });
      };
    </script>
    </html>

**Split Grid index.html**

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Split panels</title>
      <script type="text/javascript" src="https://unpkg.com/split-grid/dist/split-grid.js"></script>
    </head>
    <body>
      <div class="grid">
        <div class="column-1"></div>
        <div class="column-2"></div>
        <div class="row-1"></div>
      </div>
    </body>
    <script type="text/javascript">
      window.onload = function() {
        Split({
          columnGutters: [{
            track: 1,
            element: document.querySelector('.column-1'),
          }, {
            track: 2,
            element: document.querySelector('.column-2'),
          }],
          rowGutters: [{
            track: 1,
            element: document.querySelector('.row-1'),
          }]
        });
      };
    </script>
    </html>

**Comment by Wyzix33** [comment]
Hi,
i use it with flex layout like this:
```
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8" />
  <title>Split panels</title>
  <style>
   .gutter.gutter-vertical {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAFAQMAAABo7865AAAABlBMVEVHcEzMzMzyAv2sAAAAAXRSTlMAQObYZgAAABBJREFUeF5jOAMEEAIEEFwAn3kMwcB6I2AAAAAASUVORK5CYII=');
    cursor: col-resize;
   }
   .gutter.gutter-horizontal {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAeCAYAAADkftS9AAAAIklEQVQoU2M4c+bMfxAGAgYYmwGrIIiDjrELjpo5aiZeMwF+yNnOs5KSvgAAAABJRU5ErkJggg==');
    cursor: col-resize;
   }
   #flex {
    display: flex;
    flex-direction: row;
   }
  </style>
 </head>
 <body>
  <div id="flex">
   <div id="flex-1">aaaaa</div>
   <div id="flex-2">ssss</div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/split.js/1.5.9/split.min.js"></script>
  <script type="text/javascript">
   Split(['#flex-1', '#flex-2']);
  </script>
 </body>
</html>
```
Maybe you just need to set the css for gutter in your case
Hope it helps

**Comment by nathancahill** [comment]
@fgeorges The Split libraries do not include or set any CSS for layout. You must create a CSS layout first, then initialize Split or Split-Grid.
