### ISSUE TITLE
Cannot be used in a vue

### ISSUE THREAD

**Issue by stys35** [nathancahill/split#195]
<div id="app">
        <div class="split-parent">
            <div id="js-1">
                1
            </div>
            <div id="html-1">
                2
            </div>
            <div id="css-1">
                3
            </div>
        </div>
    </div>

it is not work

---

    <div id="app"></div>
    <div class="split-parent">
        <div id="js-1">
            1
        </div>
        <div id="html-1">
            2
        </div>
        <div id="css-1">
            3
        </div>
    </div>

---

it is  work

How to make this plugin vue compatible, thanks

**Comment by baryla** [comment]
What does your JS code look like? I'm using this with Vue and it works fine :)

**Comment by nathancahill** [comment]
@baryla I'm not very familiar with Vue, could you post a brief example on how you're using it? I can include it in the README.

**Comment by nathancahill** [comment]
Or if it's somewhat complex, we could publish a package like we do for React.

**Comment by baryla** [comment]
@nathancahill, here's a very basic demo: https://codesandbox.io/embed/vue-template-srdl4. I don't think a package is needed because I you can see from the source code, it's very minimal. :)

**Comment by nathancahill** [comment]
You are the real mvp! Thanks!

**Comment by stys35** [comment]
Thanks! I forgot the original code，i try this，and it is work！I use by CDN，
```html
    <style type="text/css">
        .wrapper {
            display: flex;
        }
        .panel{
            height: calc(100vh - 20px);
        }
        .panel__left {
            background-color: red;
        }
        .panel__right {
            background-color: blue;
        }
    </style>

    <div id="app">
        <div class="wrapper">
            <div class="panel panel__left" ref="left">
                <h1>LEFT</h1>
            </div>
            <div class="panel panel__right" ref="right">
                <h1>RIGHT</h1>
            </div>
        </div>
    </div>

    <script src="https://cdn.bootcss.com/vue/2.6.10/vue.min.js"></script>
    <script src="https://github.com/nathancahill/split/blob/master/docs/split.min.js"></script>

    <script>
        var app = new Vue({
            el: '#app',
            data: function () {
                return {
                }
            },
            mounted: function () {
                var that = this;
                Split([that.$refs.left, that.$refs.right], {
                    sizes: [50, 50]
                });
            }
        })
    </script>

```
