### ISSUE TITLE
npm package's readme logo image is broken

### ISSUE THREAD

**Issue by revelt** [nathancahill/split#196]
it's linking to https://raw.githubusercontent.com/nathancahill/split/HEAD/logo.svg
it looks like this:

![Screen Shot 2019-05-29 at 05 04 30](https://user-images.githubusercontent.com/8344688/58528692-77d26000-81cf-11e9-9017-1ffcb5e1335b.png)

thanks for making this program!

**Comment by nathancahill** [comment]
Thanks! Fixed.
