### ISSUE TITLE
react-split example

### ISSUE THREAD

**Issue by DominicTobias** [nathancahill/split#197]
Hi,

Do you have a code example of how to use this component? It's not immediately clear from the docs and an example would say a thousand words :). I'm uncertain what props I should be passing through to the components.

Doing

```jsx
<Split>
    <ComponentA />
    <ComponentB />
</Split>
```

As the Usage example suggests just throws an error `react-split.es.js:107 Uncaught TypeError: Cannot read property 'forEach' of undefined at SplitWrapper.componentDidUpdate (react-split.es.js:107)`.

Thanks

**Comment by DominicTobias** [comment]
Nevermind I will use the grid version

**Comment by anncie-pcss** [comment]
Did you solve this one? I have the same problem...

**Comment by DominicTobias** [comment]
I found this difficult to use with poor docs, couldn't get it working properly and the other ones I found were poor quality so I just did it myself from scratch

**Comment by anncie-pcss** [comment]
Ok, i get it. I found out that github documentation was not full. You should give the 'sizes' prop to the Split component:
`<Split sizes={[25, 75]}>
        <Component />
        <Component />
    </Split>`
according to p[split.js](https://split.js.org/) official website.
