### ISSUE TITLE
Basic Horizontal Split Does not Work

### ISSUE THREAD

**Issue by radiantone** [nathancahill/split#199]
Hi,
 Tried to do the most basic example possible and it did not render correctly.

https://jsfiddle.net/r7u8k0ay/

Any tips

**Comment by Wyzix33** [comment]
just add display:flex to your container
```
 <div class="" style="margin:0px;height:-webkit-calc(100vh - 120px);display:flex">
```
https://jsfiddle.net/ypLb2swq/

**Comment by nathancahill** [comment]
Thanks @Wyzix33!
