### ISSUE TITLE
react-split does not work 

### ISSUE THREAD

**Issue by mfaradzh** [nathancahill/split#200]
I cannot figure out how to make this module work with react.
=[https://codesandbox.io/s/quizzical-chaplygin-iovmm](url)

**Comment by DiscoNova** [comment]
I took a quick look at the sample and ... I'm not certain what is going on, but when I grap the splitter and move it up/down, the individual panels do get assigned a new height according to developer tools ... but that does not get rendered for some reason; your "ant-table-wrappers" remain the same size they were before the height was applied to the wrapper DIV

**Comment by nathancahill** [comment]
After dragging the handle up and down it gives me the correct sizes in the elements:

```html
<div class="ant-table-wrapper" style="height: calc(67.4825% - 5px);"></div>
<div class="gutter gutter-vertical" style="height: 10px;"></div>
<div class="ant-table-wrapper" style="height: calc(32.5175% - 5px);"></div>
```

I don't believe that the ANT tables are resizing based on the parent width.

**Comment by DiscoNova** [comment]
Actually... I think the problem is ... that the parent has no height ... or nothing to base the height calculation on...

[Modified sample](https://codesandbox.io/s/objective-wood-5oyyn) ... Unfortunately I'm not familiar with codesandbox.io so ... I may have made many unnecessary changes to the sample :D

**Comment by nathancahill** [comment]
Thanks @DiscoNova!

**Comment by mfaradzh** [comment]
@DiscoNova @nathancahill 
Thank you.
It seems that if you get rid of most styles and leave **.fullscreenContainer** with **display:flex** the module works, however ,you said that it might be because parent height is missing,  so I added to **.fullscreenContainer**  **height:number px** and still noo luck.
