### ISSUE TITLE
[react-split] sizes property not working in all cases

### ISSUE THREAD

**Issue by rassie** [nathancahill/split#201]
This is an issue followup to https://github.com/nathancahill/split/pull/187. I'm OK with PR being rejected, however, I still have a problem on my hands which I would like to see solved.

I've created a failing sandbox: https://codesandbox.io/s/ancient-darkness-gl09f. As you probably can see, clicking on the red area is supposed to maximize it (i.e. set sizes of other panes to zero). However, it fails to do so. With the patch from https://github.com/nathancahill/split/pull/187 (sandboxed in https://codesandbox.io/s/hopeful-engelbart-0hu2x) the problem is solved and I'm not aware of any side effects.

**Comment by nathancahill** [comment]
Ok, this example is much more clear, thank for bringing it up again. I'll take a look at it.
