### ISSUE TITLE
onDragEnd() called with undefined parameter

### ISSUE THREAD

**Issue by saleyn** [nathancahill/split#203]
[This fiddle](http://jsfiddle.net/saleyn/wnbgxjpz/12/) illustrates an issue that when the drag handle is moved the `onDragEnd()` function is called with `undefined` value of the `sizes` argument.  Is this a bug?  If not, how can I ensure a valid argument is passed to this function?

**Comment by Wyzix33** [comment]
If you want to use version 1.2.0, you can do this:
```
    var mySplit = Split(['#c', '#d'], {
        direction: 'vertical',
        sizes: [25, 75],
        gutterSize: 8,
        cursor: 'row-resize',
        onDragEnd: function() {
          console.log(mySplit.getSizes());        
        }
    })
```
if not just include the latest 

https://cdnjs.cloudflare.com/ajax/libs/split.js/1.5.11/split.min.js

and it will work as you tried.

Good luck

**Comment by saleyn** [comment]
It works. Thank you!
