### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Wyzix33** [nathancahill/split#205]
I'm having a lag while resizing, but only when the scrollbar appears... 
here is a screenshot 

![splitjs1](https://user-images.githubusercontent.com/13553412/62189856-be336f00-b378-11e9-9415-2491c6b73f79.jpg)
![splitjs2](https://user-images.githubusercontent.com/13553412/62189857-be336f00-b378-11e9-84e8-fa7de5919139.jpg)

As you see i get 106 ms on that line..  is this normal? or am i doing something wrong.
as for the layout, i have a simple page, here is a screenshot of the page:

![splitjs3](https://user-images.githubusercontent.com/13553412/62190329-c344ee00-b379-11e9-8ea0-94ef210eed8f.jpg)

this problem appears only when the left side has a horizontal scrollbar on the bottom.. if there is no scrollbar, there is no lag...

That tree is just a styled ul, nothing special...

Thanks

**Comment by nathancahill** [comment]
I'm guessing that the tree is constantly being redrawn by some CSS rule when the container width changes. One option is to make larger than you need, and then use `overflow: hidden` on the div in the split:

```html
<div> <!-- Split parent -->
  <div style="overflow-x: hidden"> <!-- Left side -->
    <div style="width: 600px"> <!-- Tree container -->
      <!-- Tree -->
    </div>
  </div>
  <div></div> <!-- Right side -->
</div>
```

Another option to have less redraws is to change the `dragInterval` option from `1px` to something like 10 pixels, where the split will update after 10px of drag.

**Comment by Wyzix33** [comment]
Thanks, 
```dragInterval ``` helps, I'll try to find the css rules that generates this problem
