### ISSUE TITLE
A 3 way (nested?) split question

### ISSUE THREAD

**Issue by BlakeTNC** [nathancahill/split#226]
Hi, 
This question may have been answered elsewhere, but if so I can't find it. 
- Is the split described below possible with this utility? 
- If so, is there an example that I could use? Thank you.

I'm trying to make a split that looks like this:

```
-------------
|......|....|
|----- |....|
|......|....|
-------------
```

Or here is a written description: 
1) A "main" split with a vertical split bar. (creating left and right sides)
2) The left side of the main split, is sub-split with a horizontal split bar. (creating a top left, and a bottom left).

warm regards,
Blake

**Comment by Wyzix33** [comment]
Hi, it's simple
https://codepen.io/wyzix33/pen/VwYEYZW
Hope it helps

**Comment by BlakeTNC** [comment]
Thanks much. 
That may also be a useful thing to add to the usage examples.
https://github.com/nathancahill/split/tree/master/packages/splitjs#usage-examples

**Comment by sytolk** [comment]
If this is possible in React ? I have tested with nested <Split> components but the outher Split stops dragging

**Comment by Wyzix33** [comment]
Do you get any errors/warnings? Share some code or try to replicate this behavior in a codepen.
