### ISSUE TITLE
onDrag signature incorrect

### ISSUE THREAD

**Issue by DotFreelance** [nathancahill/split#227]
It looks like the onDrag callback is documented to have this signature:
`onDrag?: sizes => void` but actually has this signature: `onDrag?: () => void`.

I don't know if this is intentional. I presume not. I think we just need to add `getSizes()` to the passed parameters, instead of nothing.

**Comment by lkesteloot** [comment]
Not sure which package you mean, but splitjs has this in the readme:

> onDragStart and onDragEnd are passed the initial and final sizes of the split since it's a common pattern to access the sizes this way.

Where does it say that onDrag will also get the sizes?

**Comment by SourceCipher** [comment]
@lkesteloot In your readme docs

![image](https://user-images.githubusercontent.com/351018/77294807-886b3e00-6ced-11ea-9c98-a1d4d616e904.png)

**Comment by nathancahill** [comment]
Fixed in 0f669c8
