### ISSUE TITLE
Dragging over iFrame stops resizing

### ISSUE THREAD

**Issue by alexthekid07** [nathancahill/split#232]
If I have an iFrame (such as in a modal bootstrap window or something of that sort) overtop a page with split.js, having the mouse cursor move overtop the iFrame while dragging will break resizing.

Video of issue: https://streamable.com/ph4yp

Is there any way to avoid this? Here's the little test HTML page from the video:
[test.zip](https://github.com/nathancahill/split/files/4355315/test.zip)

**Comment by rob-64** [comment]
@alexthekid07 

The iframe is taking the mouse event, during drag you need to disable mouse events on the iframe:

pointer-events: none !important;

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by alexthekid07** [comment]
Thank you, this worked perfect.
Just used some lazy jQuery:
```
onDragStart: function () {
	$("iframe").css("pointer-events", "none");
},
onDragEnd: function () {
	$("iframe").css("pointer-events", "auto");
}
```
