### ISSUE TITLE
Hover Cursor Not Present on Gutter in Vue JS App

### ISSUE THREAD

**Issue by cliftonlabrum** [nathancahill/split#235]
I was reading another issue and found this example: https://codesandbox.io/embed/vue-template-srdl4

Note how when you hover over the gutters, you don't get the resize cursor. They only show up after you click on the gutter.

I'm seeing the same thing in my Vue app. Any idea how to fix this? I tried using CSS to no avail:

```
.gutter {
  cursor:ew-resize;
}
.gutter:hover{
  cursor:ew-resize;
}
```
Any ideas?

**Comment by darknoll** [comment]
::v-deep .gutter {
  cursor:ew-resize;
}
::v-deep .gutter:hover{
  cursor:ew-resize;
}

**Comment by cliftonlabrum** [comment]
Thanks!
