### ISSUE TITLE
Apply to blockly?

### ISSUE THREAD

**Issue by ignatandrei** [nathancahill/split#257]
I want to apply split to separe the output from the rests of the blocks

See https://netcoreblockly.herokuapp.com/ - I want to split
the " program output " from the rest of the toolbox

I have the following
<div style="width: 100%">
        <div id="blocklyDiv"
             style="display: inline-block; height: 480px; width: 58%"></div>
        <textarea id="output"
                  style="display: inline-block; height: 480px; width: 38%;">
      
    </textarea>

    </div>

I tried to apply split.js to 
blocklyDiv 
and 
output

but the result does not show splitting.

Could you help ?
Thanks,

**Comment by NoahAndrews** [comment]
I've actually used this library in the FIRST Tech Challenge Blocks environment, which uses Blockly. You can find the source code [here](https://github.com/OpenFTC/Extracted-RC/tree/60aac018927067a95f1a919b9d6867e21f9fa532/Blocks/src/main/assets/blocks).

Specifically, use these sections as a jumping-off point:

[initializeSplit()](https://github.com/OpenFTC/Extracted-RC/blob/60aac018927067a95f1a919b9d6867e21f9fa532/Blocks/src/main/assets/blocks/FtcBlocks_common.js#L240-L249)
[resizeBlocklyArea()](https://github.com/OpenFTC/Extracted-RC/blob/60aac018927067a95f1a919b9d6867e21f9fa532/Blocks/src/main/assets/blocks/FtcBlocks_common.js#L363-L381)
[relevant HTML](https://github.com/OpenFTC/Extracted-RC/blob/60aac018927067a95f1a919b9d6867e21f9fa532/Blocks/src/main/assets/FtcBlocks.html#L190-L205)

**Comment by NoahAndrews** [comment]
Here's an offline version of our Blocks tool, so that you can see how it works without having to work with the full Robot Controller android app.

[offline_blocks_editor_demo.zip](https://github.com/nathancahill/split/files/4775289/offline_blocks_editor_demo.zip)

**Comment by ignatandrei** [comment]
Thanks. I will take a look today !

**Comment by ignatandrei** [comment]
As I understand, you did not put a split to blockly. You move blockly area to the split ;-)

**Comment by ignatandrei** [comment]
The resizeBlocklyArea works like almost magic - it is positioning over .

I do have a small problem, this is the code: 

 function initializeSplit() {
            split = window.Split([blocklyArea, output], {
                direction: 'horizontal',
                sizes: [75, 25],
                minSize: [200, 100],
                gutterSize: 4,
                snapOffset: 0,
                onDrag: resizeBlocklyArea,
            });
        }

When I call this, the output is going under the blocklyArea

You can see in production by going to 
https://netcoreblockly.herokuapp.com/

and , in the browser console, call

initializeSplit()

Could you please advise ?
Thanks
Andrei

**Comment by NoahAndrews** [comment]
After a quick look, one possibility that comes to mind is that you have blocklyDiv in the same parent div as blocklyArea. 

That being said, I just wanted to show you working code that I had already written. You're going to have to figure out why it's not entirely working for you on your own. Here's a potentially helpful bit of Blockly documentation though: https://developers.google.com/blockly/guides/configure/web/resizable

**Comment by ignatandrei** [comment]
Thank you for the answer. I am not a good designer. I have sent to you an email about this.
