### ISSUE TITLE
react-split-grid: Uncaught TypeError: Cannot read property 'only' of undefined

### ISSUE THREAD

**Issue by zenithlight** [nathancahill/split#272]
I encountered this error when trying to use react-split-grid in my application.

I believe it's related to a typo in the component's render function: https://github.com/nathancahill/split/blob/master/packages/react-split-grid/src/index.js#L185 (`Children` is spelled as `Chidren`)

**Comment by nathancahill** [comment]
Yes, that is a typo. Fix coming soon.

**Comment by nathancahill** [comment]
Fixed in 677e580
