### ISSUE TITLE
react-split: on Setting maxSize to one div, the other div also resizes.

### ISSUE THREAD

**Issue by kayesn786** [nathancahill/split#391]
Hi,

I have 3 splits (i.e. divs). I have added maxWidth to one div and while the maxwidth is met, the other divs start resizing.
I have reproduced the issue here

https://codesandbox.io/s/react-split-forked-m1f6r?file=/src/App.tsx

thanks

**Comment by rsshilli** [comment]
This is a duplicate of #66.
