### ISSUE TITLE
"Fatal" error in documented example at split.js.org

### ISSUE THREAD

**Issue by Gkleinereva** [nathancahill/split#629]
The split-grid 2-column 1-row example on split.js.org gives this HTML and CSS for the single row, 2 column case:
![image](https://user-images.githubusercontent.com/23621633/120685548-cd901180-c454-11eb-9823-e4e4326f9d15.png)
![image](https://user-images.githubusercontent.com/23621633/120685684-f6b0a200-c454-11eb-92fd-56f9dbf22ce0.png)

As I've indicated in the screenshot, the grid-column property has to be 2 so that the gutter is between the content divs.  There may be similar defects with some of the other examples but I didn't check.  I looked for the split.js.org website code in this repo, but it doesn't appear to be included.  Let me know if it's available, and I'd be happy to fix this (and any related issues)!

**Comment by nathancahill** [comment]
Thanks, fixed.
