### ISSUE TITLE
2.0.12 Typescript Error Missing Props

### ISSUE THREAD

**Issue by ifen** [nathancahill/split#689]
Seems like className prop has been removed and has broken our entire project. Is there an alternative prop to pass a class name?

**Comment by nathancahill** [comment]
Related to publishing TS types with the library. Fix will be published shortly. Sorry about the breakage.

**Comment by nathancahill** [comment]
Published the fix in react-split @ 2.0.13. Can you try with the new build please?

**Comment by ifen** [comment]
Hi @nathancahill - confirmed all is okay now! Thank you very much for the incredibly fast reply and resolution :) PS we love your package keep up the great work.
