### ISSUE TITLE
Missing index.d.ts files field of package.json in react-split-grid

### ISSUE THREAD

**Issue by ymolists** [nathancahill/split#704]
@nathancahill thank you so much for this library

I am wondering if the same declaration as [this fix](https://github.com/nathancahill/split/pull/681) missing from react-split-grid as well ? vscode is barking at me now and i am using the "react-split-grid": "^1.0.3", version in my package.json file but vscode is still unable to find the correct types

**Comment by nathancahill** [comment]
Solved and published in v1.0.4

**Comment by juhana** [comment]
Unfortunately the package still won't work with Typescript. The declaration is missing the `component` and `render` props so trying to use them causes a compilation error.

The only way to use the package with TS is by passing a function as children, but that runs into issue #573 and displays a warning in the console.

Demos here trying to use [component](https://codesandbox.io/s/react-split-grid-component-ld2rp?file=/src/App.tsx) and [render](https://codesandbox.io/s/react-split-grid-render-itjxd?file=/src/App.tsx) in a TS project.

**Comment by monting** [comment]
Thanks for a very nice library. 
Having the same issue as @juhana .. It looks like there's a few PRs that solve this.
